spring.application.name=VerificationService
server.port=8088

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id="verifierGroup"

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:verificationdb
spring.datasource.username=user
spring.datasource.password=
spring.h2.console.enabled=true